handlers:
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted
- name: reload firewalld
  command: firewall-cmd --reload
